title: Typography and Aesthetics
description: How Style Brands Present Themselves Via Typography In Relation To
  The Aesthetic Of Their Clothing
header_text: Typography and Aesthetics
footer_text: Copyright 2020 Annabelle Coleman
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
